nyu-software-engineering/profile-photo-lookup

- app/server/rekognition/tests/test_views.py
testing get_local_img() in views.py
> updated test_views

- .travis.yml
- aws_credentials.sh
Reverts nyu-software-engineering/profile-photo-lookup#83
> Revert "add AWS credentials to travis config"

- app/client/src/components/result/musician/musician.css
- app/client/src/components/result/musician/musician.jsx
> Integrate Spotify plugin with React

- app/server/crawler/occupation.py
> added improvement to athlete, user story 12 task 112 

- app/server/crawler/occupation.py
- app/server/crawler/profile.py
- app/server/crawler/views.py
- app/server/crawler/wikiAPI.py
> Refactor crawler to return celebrity profiles as JSON objects

- app/server/crawler/occupation.py
Added US president to politician type
> added president

- app/server/crawler/actor.py
- app/server/crawler/imdbAPI.py
- requirements.txt
task #136: based on an actors name, get their IMDB identification
> User story/90/task/136/actor crawling

- app/server/crawler/occupation.py
under user story 93: added specific description of world leader titles
> added world leader occupation

- app/client/src/__test__/reducer.test.js
- app/client/src/components/home/home.js
- app/client/src/components/result/actor/actor.js
- app/client/src/components/result/athlete/athlete.js
- app/client/src/components/result/celeb.js
- app/client/src/components/result/musician/musician.js
- app/client/src/components/result/musician/spotifyplaylist.js
- app/client/src/components/result/politician/politician.js
- app/client/src/components/result/resultPage.js
- app/client/src/index.js
- app/client/src/redux/analysis/action.js
- app/client/src/redux/analysis/reducer.js
- Created individual result page for each occupation
- Created accordion on main result page
> User story/129/task/131

- app/server/crawler/actor.py
getActorID takes a name and returns the imdb id associated with it
getKnownTitles tasks actor id number parses page to return lists of known titles
> update actor crawler to return a list of known titles for a given name

- app/client/src/components/home/home.css
- app/client/src/components/home/home.js
> User story/16/task/150

- app/server/crawler/musician.py
- app/server/crawler/profile.py
> Implement function to query for artist's top songs, related artists and tracks

- app/server/crawler/politician.py
task #149- added crawler to create profile on anyone who served in congress
> Added politician crawler for congress person profiles

- demo/rekognition/webscrapping.py
- demo/rekognition/wiki.py
> adding webcrawling for athletes

- utility/facebook.py
> Implement method to mass download facebook profile images

- utility/rekognition.py
> Upload facial feature vectors of profile images to AWS

- app/server/crawler/actor.py
> Implement  function to get brief overview of actor's career 

- app/client/src/redux/analysis/action.js
- app/server/rekognition/celebrity.py
- app/server/rekognition/student.py
- app/server/rekognition/urls.py
- app/server/rekognition/views.py
> Implement Rekognition API for NYU Students

- app/client/src/components/result/celeb.js
- app/client/src/components/result/musician/musician.js
- app/client/src/components/result/resultPage.css
- app/client/src/components/result/resultPage.js
> Hooked up result page to each occupation

- app/server/crawler/occupation.py
- app/server/crawler/politician.py
- app/server/crawler/profile.py
> Resolve politician first name conflict issue

- app/server/crawler/actor.py
> add upcoming films to actor crawler

- app/server/crawler/politician.py
User story #93, added presidential info (party, term served, birthday)
> User story/93/task/188/add pres info

- app/server/crawler/actor.py
> return actor info as dictionary object

- app/client/src/__test__/reducer.test.js
- app/client/src/components/home/home.js
- app/client/src/components/navbar/navbar.js
- app/client/src/components/result/resultPage.js
- app/client/src/components/student/result.css
- app/client/src/components/student/result.js
- app/client/src/components/student/student.js
- app/client/src/components/student/upload.css
- app/client/src/components/student/upload.js
- app/client/src/components/student/webcam.js
- app/client/src/components/upload/uploadDropzone.js
- app/client/src/index.js
- app/client/src/redux/analysis/action.js
- app/client/src/redux/analysis/reducer.js
- app/client/src/redux/analysis/types.js
> Refactored student upload code & styled student result page

- app/server/crawler/actor.py
- app/server/crawler/celebrity.py
- app/server/crawler/musician.py
- app/server/crawler/occupation.py
- app/server/crawler/politician.py
- app/server/crawler/profile.py
- app/server/crawler/views.py
> Apply "Factory" design pattern for celebrity profile construction

- app/server/crawler/actor.py
> implment builder design pattern in actor file

- app/server/crawler/actor.py
Reverts nyu-software-engineering/profile-photo-lookup#208
> Revert "implment builder design pattern in actor file"

- app/server/crawler/actor.py
Reverts nyu-software-engineering/profile-photo-lookup#211
> Revert "Revert "implment builder design pattern in actor file""

- app/server/crawler/musician.py
- app/server/crawler/wikiAPI.py
> Implement function to crawl for musician bio

- app/client/src/__test__/about.test.js
- app/client/src/__test__/home.test.js
- app/client/src/__test__/navbar.test.js
- app/client/src/__test__/result.test.js
- app/client/src/__test__/student.test.js
- app/client/src/__test__/upload.test.js
- app/client/src/components/result/celeb.js
- app/client/src/components/result/musician/musician.js
- app/client/src/components/result/politician/politician.css
- app/client/src/components/result/politician/politician.js
- app/client/src/components/result/resultPage.js
> Updated politician page

- app/server/crawler/occupation.py
> Fix musician occupation bug

- app/server/crawler/politician.py
- app/server/crawler/politicianstrategy.py
- app/server/crawler/test_politician.py
- app/server/crawler/tests/test_politician.py
- app/server/test_politician.py
> Implement Unit Tests for Politician

- app/server/crawler/actor.py
- app/server/crawler/tests/__init__.py
- app/server/crawler/tests/test_actor.py
> implement unit tests for actor

- app/server/crawler/actor.py
- app/server/crawler/tests/test_actor.py
> Add descriptions for known-for and upcoming films, and add additional unit tests for actor

- app/client/package.json
- app/client/src/components/notFound/notFoundPage.css
- app/client/src/components/notFound/notFoundPage.js
- app/client/src/index.js
- app/client/src/redux/analysis/action.js
> Show "no-results" page when no celebrity is detected

- app/server/crawler/occupation.py
> Implement function to distinguish celebrity's primary occupation

- app/server/crawler/occupation.py
- app/server/crawler/othercelebrity.py
- app/server/crawler/profile.py
Added public figure celebrity type for any name not recognized as an actor, musician, politician, or athlete (Ex: Michelle Obama, Albert Einstein)
> added public figure

- app/server/crawler/othercelebrity.py
- app/server/crawler/politician.py
- app/server/crawler/wikiAPI.py
> added image to info of politician and public figure

- app/client/src/__test__/reducer.test.js
- app/client/src/components/result/resultPage.css
- app/client/src/components/result/resultPage.js
- app/client/src/redux/analysis/action.js
- app/client/src/redux/analysis/reducer.js
- app/client/src/redux/analysis/types.js
> drew bounding box around faces

- app/server/crawler/actor.py
> add image property to actor

- app/client/src/components/result/actor/actor.js
- app/client/src/components/result/athlete/athlete.js
- app/client/src/components/result/musician/musician.js
- app/client/src/components/result/politician/politician.js
> updated celeb bio

- app/client/src/components/result/athlete/athlete.js
- app/client/src/components/result/resultPage.js
> vary card sizes according to number of celebs

- app/client/src/components/result/actor/actor.js
- app/client/src/components/result/athlete/athlete.js
- app/client/src/components/result/musician/musician.js
- app/server/crawler/actor.py
- app/server/crawler/athlete.py
- app/server/crawler/musician.py
- app/server/crawler/tests/test_politician.py
> Add social media icons to actor result info card
